#!/bin/zsh

set -e

if [ ! -d "$ANDROID_NDK_HOME" ]; then
	echo "Error: ANDROID_NDK_HOME is not set properly."
	exit
fi

# when trying to reproduce lldb issues, it's sometimes useful to start with a clean cache
# rm -rf ~/.lldb/module_cache || true

export PYTHONHOME="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/python3"
LLDB="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/lldb"

"$LLDB" -o "command source -s 0 -e 0 '~/.lldb/android/last-start-commands'"
