#!/bin/zsh

set -e

# when trying to reproduce lldb issues, it's sometimes useful to start with a clean cache
# rm -rf ~/.lldb/module_cache || true

echo "Using Swift toolchain at: $(swiftly use --print-location)"

swiftly run lldb -o "command source -s 0 -e 0 '~/.lldb/android/last-start-commands'"
