#!/bin/zsh

set -e

if [ "$1" != "" ]; then

	if ! adb --version > /dev/null; then
		echo "Error: adb command is no available."
		exit
	fi

	APP_ID="$1"
	APP_PID=$(adb shell pidof $APP_ID || echo -n "")

	echo "App ID: $APP_ID"
	echo "Process ID: $APP_PID"

	mkdir -p ~/.lldb/android
	cat > ~/.lldb/android/last-start-commands <<- EOF
		command alias a0 platform connect unix-abstract-connect:///$APP_ID/lldb-platform.sock
		command alias a1 process attach --pid $APP_PID
		command alias a1n process attach --name $APP_ID
		command alias a2 process handle SIGSEGV -n false -p true -s false
		command alias a3 process handle SIGBUS -n false -p true -s false
		command alias a4 process handle SIGCHLD -n false -p true -s false
		platform select remote-android
		a0
		a1
		a2
		a3
		a4
	EOF
fi

# when trying to reproduce lldb issues, it's sometimes useful to start with a clean cache
rm -rf ~/.lldb/module_cache || true

echo "Using Swift toolchain at: $(swiftly use --print-location)"

swiftly run lldb -o "command source -s 0 -e 0 '~/.lldb/android/last-start-commands'"
