#!/bin/zsh

set -e

if ! adb --version > /dev/null; then
	echo "Error: adb command is no available."
	exit
fi

if ! echo version | jdb  > /dev/null; then
	echo "Error: jdb command is no available."
	exit
fi

if [ "$1" = "" ]; then
	source /tmp/lldb-target.env
else
	APP_ID="$1"
	APP_PID=$(adb shell pidof $APP_ID || echo -n "")
fi

echo "App ID: $APP_ID"
echo "Process ID: $APP_PID"

API_LEVEL=$(adb shell getprop ro.build.version.sdk)
echo "API Level: $API_LEVEL"

PORT=$(adb forward tcp:0 jdwp:$APP_PID)
echo "JDWP Port: $PORT"
echo "threads" | jdb -attach $PORT
adb forward --remove tcp:$PORT
