#!/bin/zsh

set -e

if ! adb --version > /dev/null; then
	echo "Error: adb command is no available."
	exit
fi

if [ -f "$JAVA_HOME/bin/jdb" ]; then
	JDB="$JAVA_HOME/bin/jdb"
else
	JDB="jdb"
fi

if ! echo version | $JDB  > /dev/null; then
	echo "Error: jdb command is no available."
	exit
fi

if [ "$1" = "" ]; then
	source "$HOME/.lldb/android/last-env"
else
	APP_ID="$1"
	APP_PID=$(adb shell pidof $APP_ID || echo -n "")
fi

echo "App ID: $APP_ID"
echo "Process ID: $APP_PID"

API_LEVEL=$(adb shell getprop ro.build.version.sdk)
echo "API Level: $API_LEVEL"

PORT=$(adb forward tcp:0 jdwp:$APP_PID)
echo "JDWP Port: $PORT"

# When ART is in waiting-for-debugger mode, it actually runs in a loop,
# polling for a debugger agent every 100ms. Therefore, the agent must run
# for at least 100ms in order for the polling loop to detect it.
{ echo "version"; sleep 4 } | $JDB -attach $PORT

adb forward --remove tcp:$PORT
